/* Auto-generated by genmsg_cpp for file /home/ljentoft/Dropbox/TakkTile/tech/takktile/msg/Contact.msg */
#ifndef TAKKTILE_MESSAGE_CONTACT_H
#define TAKKTILE_MESSAGE_CONTACT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace takktile
{
template <class ContainerAllocator>
struct Contact_ {
  typedef Contact_<ContainerAllocator> Type;

  Contact_()
  : pressure()
  {
  }

  Contact_(const ContainerAllocator& _alloc)
  : pressure(_alloc)
  {
  }

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _pressure_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  pressure;


  typedef boost::shared_ptr< ::takktile::Contact_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::takktile::Contact_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Contact
typedef  ::takktile::Contact_<std::allocator<void> > Contact;

typedef boost::shared_ptr< ::takktile::Contact> ContactPtr;
typedef boost::shared_ptr< ::takktile::Contact const> ContactConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::takktile::Contact_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::takktile::Contact_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace takktile

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::takktile::Contact_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::takktile::Contact_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::takktile::Contact_<ContainerAllocator> > {
  static const char* value() 
  {
    return "620ca9b8e487092667c7d7be8066ab46";
  }

  static const char* value(const  ::takktile::Contact_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x620ca9b8e4870926ULL;
  static const uint64_t static_value2 = 0x67c7d7be8066ab46ULL;
};

template<class ContainerAllocator>
struct DataType< ::takktile::Contact_<ContainerAllocator> > {
  static const char* value() 
  {
    return "takktile/Contact";
  }

  static const char* value(const  ::takktile::Contact_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::takktile::Contact_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# message format for raw sensor data\n\
bool[] pressure\n\
\n\
";
  }

  static const char* value(const  ::takktile::Contact_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::takktile::Contact_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pressure);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Contact_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::takktile::Contact_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::takktile::Contact_<ContainerAllocator> & v) 
  {
    s << indent << "pressure[]" << std::endl;
    for (size_t i = 0; i < v.pressure.size(); ++i)
    {
      s << indent << "  pressure[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.pressure[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // TAKKTILE_MESSAGE_CONTACT_H

