/* Auto-generated by genmsg_cpp for file /home/ljentoft/Dropbox/TakkTile/tech/takktile/msg/Touch.msg */
#ifndef TAKKTILE_MESSAGE_TOUCH_H
#define TAKKTILE_MESSAGE_TOUCH_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace takktile
{
template <class ContainerAllocator>
struct Touch_ {
  typedef Touch_<ContainerAllocator> Type;

  Touch_()
  : pressure()
  {
  }

  Touch_(const ContainerAllocator& _alloc)
  : pressure(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pressure_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  pressure;


  typedef boost::shared_ptr< ::takktile::Touch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::takktile::Touch_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Touch
typedef  ::takktile::Touch_<std::allocator<void> > Touch;

typedef boost::shared_ptr< ::takktile::Touch> TouchPtr;
typedef boost::shared_ptr< ::takktile::Touch const> TouchConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::takktile::Touch_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::takktile::Touch_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace takktile

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::takktile::Touch_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::takktile::Touch_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::takktile::Touch_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a3d699886be367f8749f5edfbaab0ff";
  }

  static const char* value(const  ::takktile::Touch_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4a3d699886be367fULL;
  static const uint64_t static_value2 = 0x8749f5edfbaab0ffULL;
};

template<class ContainerAllocator>
struct DataType< ::takktile::Touch_<ContainerAllocator> > {
  static const char* value() 
  {
    return "takktile/Touch";
  }

  static const char* value(const  ::takktile::Touch_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::takktile::Touch_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# message format for raw sensor data\n\
float32[] pressure\n\
\n\
";
  }

  static const char* value(const  ::takktile::Touch_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::takktile::Touch_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pressure);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Touch_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::takktile::Touch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::takktile::Touch_<ContainerAllocator> & v) 
  {
    s << indent << "pressure[]" << std::endl;
    for (size_t i = 0; i < v.pressure.size(); ++i)
    {
      s << indent << "  pressure[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pressure[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // TAKKTILE_MESSAGE_TOUCH_H

